#Informing the user about the script
#In this activity, you will start a new Python script by creating the initial output that informs the user about what the script will do.
#From the menu bar, choose File > New From Template > Python File.
#Delete the provided sample code from the template file.
#Choose File > Save As... and save it as for-loop.py.
#To inform the user about your script, use the print() function:
print("Count to 10!")
#Save and run the file.
#Confirm that the script runs correctly and that the output displays as you expect it to.

#Writing the for loop
#In Python, you can include a large amount of functionality in a few words. This feature makes Python relatively easy to write compared to other programming languages, but it can also make Python code more difficult to read. In this activity, you will use the for statement, but you will also spend some time analyzing it after you see it run.
#Return to the Python script. To count to 10, enter the following code.
#Note: Python uses indentation to determine that the print statement is inside the for loop statement.):
for x in range (0, 11):
    print(x)

#Save and run the file.

#Confirm that the script runs correctly and that the output displays as you expect it to.
#Here is an explanation of what happened in those two lines. The for statement uses the for … in keywords to tell the computer to go through the list. A list is generated by the range() function. The range() function takes a starting number and an ending number, but the ending number is not inclusive. Therefore, you pass in 11 to have the function stop counting at 10. The letter x acts as a variable. Each time through the loop, the variable x is assigned to the next variable in the loop and is printed out to the screen.
